version: "3.9"


services:
  mysql:
    image: mysql:8.0.26
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: TesloDB
      MYSQL_ROOT_PASSWORD: mysecretpassword
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"